// Courses
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';

export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const GET_COURSE_BY_ID_SUCCESS = 'GET_COURSE_BY_ID_SUCCESS';