// Courses
export const GET_COURSES = 'GET_COURSES';
export const DELETE_COURSE = 'DELETE_COURSE';
export const CREATE_COURSE = 'CREATE_COURSE';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const CLEAN_FILTER = 'CLEAN_FILTER';

export const UPDATE_COURSE = 'UPDATE_COURSE';
export const GET_COURSE_BY_ID = 'GET_COURSE_BY_ID';
export const UPDATE_COURSE_FIELD = 'UPDATE_COURSE_FIELD';
export const CHANGE_COURSE_FIELD = 'CHANGE_COURSE_FIELD';
export const GET_DEFAULT_COURSE = 'GET_DEFAULT_COURSE';